
import React, { useState, useEffect } from 'react';
import { Modal, Button } from './UI';
import { Copy, Check, Terminal, Sparkles, Loader2, Cpu, Wrench, ShieldCheck, AlertTriangle } from 'lucide-react';
import { GoogleGenAI } from "@google/genai";
import { api } from '../services/api';
import { CircuitAnalysis } from '../types';

interface CodeViewerProps {
  isOpen: boolean;
  onClose: () => void;
  mode: 'circuit' | 'training';
  data: any; // Flexible data input based on mode
}

export const CodeViewer: React.FC<CodeViewerProps> = ({ isOpen, onClose, mode, data }) => {
  const [code, setCode] = useState('');
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<'code' | 'analysis'>('code');
  const [analysis, setAnalysis] = useState<CircuitAnalysis | null>(null);
  const [analyzing, setAnalyzing] = useState(false);

  useEffect(() => {
    if (isOpen) {
        const generated = generateCode();
        setCode(generated);
        setAnalysis(null);
        setActiveTab('code');
    }
  }, [isOpen, data]);

  const generateCode = () => {
      let script = "";
      
      if (mode === 'circuit') {
          // Generate Qiskit Circuit Code
          script = `# Generated by Qore Platform
import numpy as np
from qiskit import QuantumCircuit, transpile
from qiskit_aer import AerSimulator

# 1. Initialize Circuit
n_qubits = ${data.qubits || 4}
qc = QuantumCircuit(n_qubits)

# 2. Apply Gates (Visualized Steps)
`;
          if (data.circuit && data.circuit.length > 0) {
              data.circuit.forEach((g: any) => {
                  if (g.type === 'H') script += `qc.h(${g.target})\n`;
                  else if (g.type === 'X') script += `qc.x(${g.target})\n`;
                  else if (g.type === 'Z') script += `qc.z(${g.target})\n`;
                  else if (g.type === 'CNOT') script += `qc.cx(${g.target-1}, ${g.target}) # Assumed control neighbor\n`;
              });
          } else {
              // Placeholder for auto-generated ansatz visualization
              script += `# Hardware Efficient Ansatz Structure
for i in range(n_qubits):
    qc.ry(np.pi/4, i)
for i in range(n_qubits-1):
    qc.cx(i, i+1)
`;
          }

          script += `
# 3. Measurement
qc.measure_all()

# 4. Execution
simulator = AerSimulator()
compiled_circuit = transpile(qc, simulator)
job = simulator.run(compiled_circuit, shots=1024)
result = job.result()
counts = result.get_counts(qc)
print(f"Counts: {counts}")
`;
      } else {
          // Generate VQC Training Code
          script = `# Generated by Qore Platform - VQC Training
import torch
from torch.nn import functional as F
from qiskit_machine_learning.neural_networks import EstimatorQNN
from qiskit.circuit.library import RealAmplitudes, ZZFeatureMap
from qiskit import QuantumCircuit

# 1. Configuration
DATASET = "${data.dataset}"
EPOCHS = ${data.epochs}
LEARNING_RATE = ${data.lr}
LAYERS = ${data.layers}

# 2. Feature Map & Ansatz
num_qubits = 4 # Based on Iris/Wine features
feature_map = ZZFeatureMap(feature_dimension=num_qubits, reps=2)
ansatz = RealAmplitudes(num_qubits=num_qubits, reps=LAYERS)

# 3. Quantum Neural Network
qc = QuantumCircuit(num_qubits)
qc.append(feature_map, range(num_qubits))
qc.append(ansatz, range(num_qubits))

# Note: This requires Qiskit Machine Learning installed
# qnn = EstimatorQNN(
#    circuit=qc,
#    input_params=feature_map.parameters,
#    weight_params=ansatz.parameters
# )

# 4. Optimization Loop (Mock Structure)
print(f"Starting training on {DATASET} for {EPOCHS} epochs...")
for epoch in range(EPOCHS):
    # optimizer.step()
    print(f"Epoch {epoch+1}/{EPOCHS} complete.")
`;
      }
      return script;
  };

  const handleCopy = () => {
      navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
  };

  const runAnalysis = async () => {
      setAnalyzing(true);
      try {
          const result = await api.analyzeQuantumCode(code);
          setAnalysis(result);
      } catch (e) {
          console.error(e);
      } finally {
          setAnalyzing(false);
      }
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title={mode === 'circuit' ? "Qiskit Circuit Export" : "VQC Training Script"}>
        <div className="flex flex-col h-[500px]">
            
            {/* Tabs */}
            <div className="flex gap-4 border-b border-slate-200 dark:border-slate-800 mb-4">
                <button 
                    onClick={() => setActiveTab('code')}
                    className={`pb-2 text-sm font-bold border-b-2 transition-colors ${activeTab === 'code' ? 'border-violet-600 text-violet-600 dark:text-violet-400' : 'border-transparent text-slate-500'}`}
                >
                    Source Code
                </button>
                <button 
                    onClick={() => { setActiveTab('analysis'); if(!analysis) runAnalysis(); }}
                    className={`pb-2 text-sm font-bold border-b-2 transition-colors flex items-center gap-2 ${activeTab === 'analysis' ? 'border-violet-600 text-violet-600 dark:text-violet-400' : 'border-transparent text-slate-500'}`}
                >
                    <Sparkles className="w-3 h-3"/> AI Audit
                </button>
            </div>

            <div className="flex-grow overflow-hidden relative">
                {/* SOURCE CODE VIEW */}
                {activeTab === 'code' && (
                    <div className="h-full flex flex-col">
                        <div className="bg-[#1e1e1e] rounded-xl overflow-hidden border border-slate-800 shadow-inner flex-grow flex flex-col">
                            <div className="flex items-center justify-between px-4 py-2 bg-[#252526] border-b border-black/20">
                                <div className="flex gap-1.5">
                                    <div className="w-3 h-3 rounded-full bg-red-500/80"></div>
                                    <div className="w-3 h-3 rounded-full bg-amber-500/80"></div>
                                    <div className="w-3 h-3 rounded-full bg-emerald-500/80"></div>
                                </div>
                                <Button 
                                    variant="soft" 
                                    className="text-[10px] h-6 px-2 bg-slate-700 hover:bg-slate-600 text-slate-200 border-slate-600"
                                    onClick={handleCopy}
                                >
                                    {copied ? 'Copied' : 'Copy'}
                                </Button>
                            </div>
                            <div className="p-4 overflow-x-auto custom-scrollbar flex-grow">
                                <pre className="font-mono text-sm text-blue-100 leading-relaxed">
                                    <code>{code}</code>
                                </pre>
                            </div>
                        </div>
                        <p className="mt-2 text-[10px] text-slate-400 text-center">Compatible with Qiskit 1.0+</p>
                    </div>
                )}

                {/* AI ANALYSIS VIEW */}
                {activeTab === 'analysis' && (
                    <div className="h-full overflow-y-auto custom-scrollbar pr-2 space-y-6 animate-fade-in">
                        {analyzing ? (
                            <div className="h-full flex flex-col items-center justify-center text-slate-400">
                                <Loader2 className="w-8 h-8 animate-spin mb-2 text-violet-500"/>
                                <p className="text-sm">Analyzing circuit topology...</p>
                            </div>
                        ) : analysis ? (
                            <>
                                <div className="p-4 bg-violet-50 dark:bg-violet-900/20 rounded-xl border border-violet-100 dark:border-violet-800">
                                    <h4 className="text-sm font-bold text-violet-800 dark:text-violet-300 mb-2 flex items-center gap-2">
                                        <Sparkles className="w-4 h-4"/> Intelligence Summary
                                    </h4>
                                    <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
                                        {analysis.summary}
                                    </p>
                                </div>

                                <div>
                                    <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-3 flex items-center gap-2">
                                        <Wrench className="w-3 h-3"/> Optimization Suggestions
                                    </h4>
                                    <div className="space-y-2">
                                        {analysis.optimizations.map((opt, i) => (
                                            <div key={i} className="flex items-start gap-3 p-3 bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700">
                                                <Check className="w-4 h-4 text-emerald-500 mt-0.5 flex-shrink-0"/>
                                                <span className="text-sm text-slate-700 dark:text-slate-300">{opt}</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>

                                <div>
                                    <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-3 flex items-center gap-2">
                                        <Cpu className="w-3 h-3"/> Hardware Compilation Check
                                    </h4>
                                    <div className="grid grid-cols-1 gap-3">
                                        <HardwareStatus name="IBM Eagle (127q)" status={analysis.hardwareCompatibility.ibm} />
                                        <HardwareStatus name="Rigetti Ankaa (84q)" status={analysis.hardwareCompatibility.rigetti} />
                                        <HardwareStatus name="IonQ Aria (25q)" status={analysis.hardwareCompatibility.ionq} />
                                    </div>
                                </div>
                            </>
                        ) : (
                            <div className="text-center py-10">
                                <Button onClick={runAnalysis} icon={<Sparkles className="w-4 h-4"/>}>Run Analysis</Button>
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    </Modal>
  );
};

const HardwareStatus: React.FC<{ name: string; status: { compatible: boolean; reason: string } }> = ({ name, status }) => (
    <div className={`p-3 rounded-lg border flex items-start gap-3 ${status.compatible ? 'bg-emerald-50/50 dark:bg-emerald-900/10 border-emerald-100 dark:border-emerald-800' : 'bg-red-50/50 dark:bg-red-900/10 border-red-100 dark:border-red-800'}`}>
        {status.compatible ? <ShieldCheck className="w-5 h-5 text-emerald-500 flex-shrink-0" /> : <AlertTriangle className="w-5 h-5 text-red-500 flex-shrink-0" />}
        <div>
            <div className="flex justify-between items-center mb-1">
                <span className="font-bold text-sm text-slate-800 dark:text-slate-200">{name}</span>
                <span className={`text-[10px] font-bold px-2 py-0.5 rounded ${status.compatible ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/50 dark:text-emerald-300' : 'bg-red-100 text-red-700 dark:bg-red-900/50 dark:text-red-300'}`}>
                    {status.compatible ? 'COMPATIBLE' : 'NEEDS TRANSPILE'}
                </span>
            </div>
            <p className="text-xs text-slate-500 dark:text-slate-400">{status.reason}</p>
        </div>
    </div>
);
